### PR TITLE
bugfix: observe IsReadOnly property of TextBox

### PR DESCRIPTION
**Pull request by ronnieoverby**

### CODE REVIEW

**Comment by ronnieoverby** [comment]
plans for nuget update?

**Comment by abbaye** [comment]
If you need yes I can this afternoon :)

**Comment by ronnieoverby** [comment]
That would be perfect. Thanks!

**Comment by abbaye** [comment]
Package updated. (just few minutes for index on nuget)

Thank Ronnie for support

**Comment by ronnieoverby** [comment]
Awesome. Thank you.

**Pull request merged**
